site_name: Donation Receipts
site_description: 'Documentation for the Donation Receipts Extension (de.systopia.donrec)'
site_author: SYSTOPIA
repo_url: https://github.com/systopia/de.systopia.donrec

theme:
  name: material

nav:
  - 'Preface': index.md
  - 'Installation': installation.md
  - 'Usage':
      - 'Creating donation receipts': usage/creating-donation-receipts.md
      - '"Donation Receipts" tab on the contact page': usage/donation-receipts-tab-contact-page.md
      - 'Miscellaneous': usage/miscellaneous.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - pymdownx.highlight:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
